services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test_postgres
      POSTGRES_PASSWORD: test_postgres
      POSTGRES_DB: balancer
    volumes:
      - ./.local/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - ./.local/redis-data:/data