name: Backend DEV Docker Image

on:
  push:
    branches: [ workspaceRewrite ]
  pull_request:
    branches: [ workspaceRewrite ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Login to Registry
      uses: docker/login-action@v3
      with:
        registry: owbalancer.ddns.net
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: 'image=moby/buildkit:v0.10.5'
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
          file: ./Dockerfile
          push: true
          tags: owbalancer.ddns.net/${{ secrets.DOCKER_HUB_USERNAME }}/owbalancer-dev-backend:latest
